#ifndef _TD_VENDOR_OPERATIONS_H_
#define _TD_VENDOR_OPERATIONS_H_


#include "td_bcm_operations.h"
#define TD_FRAME_BIT_PROBE_REQ (1 << TD_PE_FRAME_TYPE_PROBE_REQ)
#define TD_FRAME_BIT_BEACON    (1 << TD_PE_FRAME_TYPE_BEACON   )
#define TD_FRAME_BIT_PROBE_RES (1 << TD_PE_FRAME_TYPE_PROBE_RES)
#define TD_FRAME_BIT_ASSOC_REQ (1 << TD_PE_FRAME_TYPE_ASSOC_REQ)
#define TD_FRAME_BIT_ASSOC_RES (1 << TD_PE_FRAME_TYPE_ASSOC_RES)
#define TD_FRAME_BIT_AUTH      (1 << TD_PE_FRAME_TYPE_AUTH     )


#endif
