
/* shmdefs structure for ucode_std - 30 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_30 = 
{
	.common_base = &common_base_ucode_std_30,
	.proxd = &proxd_ucode_std_30,
	.mcnx = &mcnx_ucode_std_30,
	.p2p = &p2p_ucode_std_30,
	.mfgtest = &mfgtest_ucode_std_30,
	.km = &km_ucode_std_30,
	.txbf = &txbf_ucode_std_30,
	.macstat = &macstat_ucode_std_30,
	.mbssid = &mbssid_ucode_std_30,
	.physim = &physim_ucode_std_30,
	.ulpphysim = &ulpphysim_ucode_std_30,
	.btcx = &btcx_ucode_std_30,
	.ltecx = &ltecx_ucode_std_30,
	.ccastat = &ccastat_ucode_std_30,
	.ampdu = &ampdu_ucode_std_30,
	.btamp = &btamp_ucode_std_30,
	.rev_ge_40 = &rev_ge_40_ucode_std_30,
	.rev_lt_40 = &rev_lt_40_ucode_std_30,
	.bcntrim = &bcntrim_ucode_std_30,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_30,
	.wowl = &wowl_ucode_std_30,
	.bcmulp = &bcmulp_ucode_std_30,
	.tsync = &tsync_ucode_std_30,
	.ops = &ops_ucode_std_30,
	.rev_ge_64 = &rev_ge_64_ucode_std_30,
	.rev_ge_128 = &rev_ge_128_ucode_std_30,
	.eap = &eap_ucode_std_30,
};

/* shmdefs structure for ucode_std - 42 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_42 = 
{
	.common_base = &common_base_ucode_std_42,
	.proxd = &proxd_ucode_std_42,
	.mcnx = &mcnx_ucode_std_42,
	.p2p = &p2p_ucode_std_42,
	.mfgtest = &mfgtest_ucode_std_42,
	.km = &km_ucode_std_42,
	.txbf = &txbf_ucode_std_42,
	.macstat = &macstat_ucode_std_42,
	.mbssid = &mbssid_ucode_std_42,
	.physim = &physim_ucode_std_42,
	.ulpphysim = &ulpphysim_ucode_std_42,
	.btcx = &btcx_ucode_std_42,
	.ltecx = &ltecx_ucode_std_42,
	.ccastat = &ccastat_ucode_std_42,
	.ampdu = &ampdu_ucode_std_42,
	.btamp = &btamp_ucode_std_42,
	.rev_ge_40 = &rev_ge_40_ucode_std_42,
	.rev_lt_40 = &rev_lt_40_ucode_std_42,
	.bcntrim = &bcntrim_ucode_std_42,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_42,
	.wowl = &wowl_ucode_std_42,
	.bcmulp = &bcmulp_ucode_std_42,
	.tsync = &tsync_ucode_std_42,
	.ops = &ops_ucode_std_42,
	.rev_ge_64 = &rev_ge_64_ucode_std_42,
	.rev_ge_128 = &rev_ge_128_ucode_std_42,
	.eap = &eap_ucode_std_42,
};

/* shmdefs structure for ucode_std - 49 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_49 = 
{
	.common_base = &common_base_ucode_std_49,
	.proxd = &proxd_ucode_std_49,
	.mcnx = &mcnx_ucode_std_49,
	.p2p = &p2p_ucode_std_49,
	.mfgtest = &mfgtest_ucode_std_49,
	.km = &km_ucode_std_49,
	.txbf = &txbf_ucode_std_49,
	.macstat = &macstat_ucode_std_49,
	.mbssid = &mbssid_ucode_std_49,
	.physim = &physim_ucode_std_49,
	.ulpphysim = &ulpphysim_ucode_std_49,
	.btcx = &btcx_ucode_std_49,
	.ltecx = &ltecx_ucode_std_49,
	.ccastat = &ccastat_ucode_std_49,
	.ampdu = &ampdu_ucode_std_49,
	.btamp = &btamp_ucode_std_49,
	.rev_ge_40 = &rev_ge_40_ucode_std_49,
	.rev_lt_40 = &rev_lt_40_ucode_std_49,
	.bcntrim = &bcntrim_ucode_std_49,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_49,
	.wowl = &wowl_ucode_std_49,
	.bcmulp = &bcmulp_ucode_std_49,
	.tsync = &tsync_ucode_std_49,
	.ops = &ops_ucode_std_49,
	.rev_ge_64 = &rev_ge_64_ucode_std_49,
	.rev_ge_128 = &rev_ge_128_ucode_std_49,
	.eap = &eap_ucode_std_49,
};

/* shmdefs structure for ucode_std - 65 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_65 = 
{
	.common_base = &common_base_ucode_std_65,
	.proxd = &proxd_ucode_std_65,
	.mcnx = &mcnx_ucode_std_65,
	.p2p = &p2p_ucode_std_65,
	.mfgtest = &mfgtest_ucode_std_65,
	.km = &km_ucode_std_65,
	.txbf = &txbf_ucode_std_65,
	.macstat = &macstat_ucode_std_65,
	.mbssid = &mbssid_ucode_std_65,
	.physim = &physim_ucode_std_65,
	.ulpphysim = &ulpphysim_ucode_std_65,
	.btcx = &btcx_ucode_std_65,
	.ltecx = &ltecx_ucode_std_65,
	.ccastat = &ccastat_ucode_std_65,
	.ampdu = &ampdu_ucode_std_65,
	.btamp = &btamp_ucode_std_65,
	.rev_ge_40 = &rev_ge_40_ucode_std_65,
	.rev_lt_40 = &rev_lt_40_ucode_std_65,
	.bcntrim = &bcntrim_ucode_std_65,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_65,
	.wowl = &wowl_ucode_std_65,
	.bcmulp = &bcmulp_ucode_std_65,
	.tsync = &tsync_ucode_std_65,
	.ops = &ops_ucode_std_65,
	.rev_ge_64 = &rev_ge_64_ucode_std_65,
	.rev_ge_128 = &rev_ge_128_ucode_std_65,
	.eap = &eap_ucode_std_65,
};

/* shmdefs structure for ucode_std - 129 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_129 = 
{
	.common_base = &common_base_ucode_std_129,
	.proxd = &proxd_ucode_std_129,
	.mcnx = &mcnx_ucode_std_129,
	.p2p = &p2p_ucode_std_129,
	.mfgtest = &mfgtest_ucode_std_129,
	.km = &km_ucode_std_129,
	.txbf = &txbf_ucode_std_129,
	.macstat = &macstat_ucode_std_129,
	.mbssid = &mbssid_ucode_std_129,
	.physim = &physim_ucode_std_129,
	.ulpphysim = &ulpphysim_ucode_std_129,
	.btcx = &btcx_ucode_std_129,
	.ltecx = &ltecx_ucode_std_129,
	.ccastat = &ccastat_ucode_std_129,
	.ampdu = &ampdu_ucode_std_129,
	.btamp = &btamp_ucode_std_129,
	.rev_ge_40 = &rev_ge_40_ucode_std_129,
	.rev_lt_40 = &rev_lt_40_ucode_std_129,
	.bcntrim = &bcntrim_ucode_std_129,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_129,
	.wowl = &wowl_ucode_std_129,
	.bcmulp = &bcmulp_ucode_std_129,
	.tsync = &tsync_ucode_std_129,
	.ops = &ops_ucode_std_129,
	.rev_ge_64 = &rev_ge_64_ucode_std_129,
	.rev_ge_128 = &rev_ge_128_ucode_std_129,
	.eap = &eap_ucode_std_129,
};

/* shmdefs structure for ucode_std - 130 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_130 = 
{
	.common_base = &common_base_ucode_std_130,
	.proxd = &proxd_ucode_std_130,
	.mcnx = &mcnx_ucode_std_130,
	.p2p = &p2p_ucode_std_130,
	.mfgtest = &mfgtest_ucode_std_130,
	.km = &km_ucode_std_130,
	.txbf = &txbf_ucode_std_130,
	.macstat = &macstat_ucode_std_130,
	.mbssid = &mbssid_ucode_std_130,
	.physim = &physim_ucode_std_130,
	.ulpphysim = &ulpphysim_ucode_std_130,
	.btcx = &btcx_ucode_std_130,
	.ltecx = &ltecx_ucode_std_130,
	.ccastat = &ccastat_ucode_std_130,
	.ampdu = &ampdu_ucode_std_130,
	.btamp = &btamp_ucode_std_130,
	.rev_ge_40 = &rev_ge_40_ucode_std_130,
	.rev_lt_40 = &rev_lt_40_ucode_std_130,
	.bcntrim = &bcntrim_ucode_std_130,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_130,
	.wowl = &wowl_ucode_std_130,
	.bcmulp = &bcmulp_ucode_std_130,
	.tsync = &tsync_ucode_std_130,
	.ops = &ops_ucode_std_130,
	.rev_ge_64 = &rev_ge_64_ucode_std_130,
	.rev_ge_128 = &rev_ge_128_ucode_std_130,
	.eap = &eap_ucode_std_130,
};

/* shmdefs structure for ucode_std - 131 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_131 = 
{
	.common_base = &common_base_ucode_std_131,
	.proxd = &proxd_ucode_std_131,
	.mcnx = &mcnx_ucode_std_131,
	.p2p = &p2p_ucode_std_131,
	.mfgtest = &mfgtest_ucode_std_131,
	.km = &km_ucode_std_131,
	.txbf = &txbf_ucode_std_131,
	.macstat = &macstat_ucode_std_131,
	.mbssid = &mbssid_ucode_std_131,
	.physim = &physim_ucode_std_131,
	.ulpphysim = &ulpphysim_ucode_std_131,
	.btcx = &btcx_ucode_std_131,
	.ltecx = &ltecx_ucode_std_131,
	.ccastat = &ccastat_ucode_std_131,
	.ampdu = &ampdu_ucode_std_131,
	.btamp = &btamp_ucode_std_131,
	.rev_ge_40 = &rev_ge_40_ucode_std_131,
	.rev_lt_40 = &rev_lt_40_ucode_std_131,
	.bcntrim = &bcntrim_ucode_std_131,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_131,
	.wowl = &wowl_ucode_std_131,
	.bcmulp = &bcmulp_ucode_std_131,
	.tsync = &tsync_ucode_std_131,
	.ops = &ops_ucode_std_131,
	.rev_ge_64 = &rev_ge_64_ucode_std_131,
	.rev_ge_128 = &rev_ge_128_ucode_std_131,
	.eap = &eap_ucode_std_131,
};

/* shmdefs structure for ucode_std - 132 */
static const shmdefs_t d11shm_struct_ucode_std_d11rev_132 = 
{
	.common_base = &common_base_ucode_std_132,
	.proxd = &proxd_ucode_std_132,
	.mcnx = &mcnx_ucode_std_132,
	.p2p = &p2p_ucode_std_132,
	.mfgtest = &mfgtest_ucode_std_132,
	.km = &km_ucode_std_132,
	.txbf = &txbf_ucode_std_132,
	.macstat = &macstat_ucode_std_132,
	.mbssid = &mbssid_ucode_std_132,
	.physim = &physim_ucode_std_132,
	.ulpphysim = &ulpphysim_ucode_std_132,
	.btcx = &btcx_ucode_std_132,
	.ltecx = &ltecx_ucode_std_132,
	.ccastat = &ccastat_ucode_std_132,
	.ampdu = &ampdu_ucode_std_132,
	.btamp = &btamp_ucode_std_132,
	.rev_ge_40 = &rev_ge_40_ucode_std_132,
	.rev_lt_40 = &rev_lt_40_ucode_std_132,
	.bcntrim = &bcntrim_ucode_std_132,
	.rev_sslp_lt_40 = &rev_sslp_lt_40_ucode_std_132,
	.wowl = &wowl_ucode_std_132,
	.bcmulp = &bcmulp_ucode_std_132,
	.tsync = &tsync_ucode_std_132,
	.ops = &ops_ucode_std_132,
	.rev_ge_64 = &rev_ge_64_ucode_std_132,
	.rev_ge_128 = &rev_ge_128_ucode_std_132,
	.eap = &eap_ucode_std_132,
};
