#
# Automatically generated make config: don't edit
# ugw Configuration
#

#
# basic system info
#

#
# chip select
#
BROADCOM=y
# RaLink is not set
# Realtek is not set
# BCM4708 is not set
# BCM4709C0 is not set
# BCM47189 is not set
# BCM4706 is not set
# BCM5356C0 is not set
# BCM53573 is not set
# BCM96755 is not set
BCM96756=y
# SWITCH_BROADCOM is not set
# SWITCH_REALTEK is not set
SWITCH_NONE=y
ETHERNET_PHY_NONE=y
# BCM4360_11ACWL14_93 is not set
# BCM4360_11AC is not set
# BCM4331 is not set
# BCM4709_178_27 is not set
# BCM_47189 is not set
# RTL8196e_WIFI is not set
# RTL8197f_WIFI is not set
# CONFIG_WIFI_BCM6755 is not set
CONFIG_WIFI_BCM6756=y
CONFIG_CHIP_VENDER=broadcom
CONFIG_WIFI_CHIP=bcm6755

#
# Configuration mtd selection and size
#
CONFIG_MTD_ALL_SIZE=0x1000000
CONFIG_MTD_CFM_SIZE=0x0010000
CONFIG_MTD_NVRAM_SIZE=0x0010000
# CONFIG_CFM_WEBFS is not set
# CONFIG_URL_MTD is not set
CONFIG_CFM_BACKUP=y
# CONFIG_PICTURE is not set
# CONFIG_POLICY is not set
# CONFIG_LOG is not set
CONFIG_USE_SQUASHFS=y
# CONFIG_BOOT_FROM_SPIFLASH is not set

#
# Product infomation
#
CONFIG_PRODUCT=AX12_PRO
CONFIG_PRODUCT_NAME=
CONFIG_BRAND=IP-COM
CONFIG_LOGIN_DOMAIN_NAME=www.tendawifi.com
# CONFIG_WAN_LEFT is not set
# CONFIG_LAN_LEFT is not set
# CONFIG_WAN_LAN_COUNT_FROM_ZERO is not set
# CONFIG_LAN_COUNT_BASE_ON_WAN is not set
# CONFIG_WAN_LAN_EXCHANGE is not set
# CONFIG_WAN_STOPPAGE_CHECK is not set
# CONFIG_WAN_SAME_VLAN is not set

#
# PHY speed settings
#
CONFIG_WAN_IP_CONFLICT_AUTO_HANDLE=y
# CONFIG_UI_QUICK_CONFIG is not set
# CONFIG_MULTI_LANGUAGE_SORFWARE is not set
# CONFIG_SUPPORT_HTTP_KEEP_ALIVE is not set
# CONFIG_UI_LOGIN_USERNAME_SUPPORT is not set
# CONFIG_MESH_FEATURES is not set
# CONFIG_PHY_SETTINGS is not set
CONFIG_ALL_FE=y
# CONFIG_TWO_FE is not set
CONFIG_PROD=y
CONFIG_NEW_NETCTRL=y
# CONFIG_PORT_PIC_VIEW is not set
# CONFIG_DHCPS_CHANGE_DOWN_LAN_PHY_CONNECT is not set

#
# major feature
#

#
# common driver
#
CONFIG_WAN_AUTO_DETECT=y
CONFIG_COMM_GPIO=y
CONFIG_PHY_CHECK=y
# CONFIG_SWITCH is not set
# CONFIG_SWITCH_MISC_MODE is not set
# CONFIG_ETHERNET_PHY_API_DRV is not set
# CONFIG_ETHERNET is not set

#
# ipv6
#
CONFIG_IPV6_SUPPORT=y
# SUPPORT_HTTP_IPV6 is not set
CONFIG_IPV6_NAT66=y

#
# wifi
#
CONFIG_CE_POWER=y
# CONFIG_CE_POWER_TSSI is not set
# CONFIG_WIFI_POWER_ADJUST is not set
CONFIG_WIFI=y
CONFIG_WIFI6=y
# CONFIG_WIFI_CHINESE_SSID is not set
# CONFIG_WIFI_2_4G_CHIP_BCM_ARM is not set
# CONFIG_WIFI_2_4G_CHIP_11AC is not set
CONFIG_WIFI_2_4G_CHIP_PRE=0:
CONFIG_WIFI_5G_CHIP_PRE=1:
# CONFIG_WIFI_APSTA is not set
# CONFIG_WIFI_AUTH_1X is not set
# CONFIG_WIFI_POWER_REGULATE is not set
CONFIG_WIFI_WPS=y
# CONFIG_ALEXA_WIFI_WPS_SET is not set
# CONFIG_WIFI_BTN is not set
# CONFIG_WIFI_AC is not set
# CONFIG_WIFI_EMF is not set
CONFIG_WIFI_2_4G=y
CONFIG_WIFI_5G=y
CONFIG_WIFI_WISP=y
CONFIG_WIFI_GUEST=y
# CONFIG_SET_GUEST_SSID is not set
CONFIG_ALEXA_GUSET_WIFI_SET=y
CONFIG_WIFI_SUPPORT_SWITCH=y
# CONFIG_WIFI_ANTJ is not set
# CONFIG_WIFI_FATAL_ERROR_MONITOR is not set
CONFIG_WIFI_FILTER_NUMBER=32
CONFIG_SSID_MAC_FILTER_NUMBER=64
CONFIG_WIFI_FILTER_ADD_NUMBER=5
CONFIG_2_4G_MAX_SSID_NUMBER=8
CONFIG_5G_MAX_SSID_NUMBER=8
# CONFIG_SCHED_WIFI is not set
CONFIG_24G_PCI1=y
# CONFIG_24G_PCI2 is not set
# CONFIG_24G_PCI3 is not set
CONFIG_5G_PCI1=y
# CONFIG_5G_PCI2 is not set
# CONFIG_5G_PCI3 is not set
# CONFIG_AUTO_SSID_HIDE is not set
# CONFIG_INTERFERENCE_MODE is not set
# CONFIG_RSSI_MANAGE is not set
# CONFIG_RECV_SENSITIVITY is not set
# CONFIG_WL_PRIO_5G is not set
# CONFIG_PROBE_BROADCAST_SUPPRESSION is not set
# CONFIG_WL_PRIO_ICMP is not set
# CONFIG_TENDA_WLAN_DBG is not set
# CONFIG_WL_RATE_OPTIMIZE is not set
# CONFIG_WL_DHCP_OPTIMIZE is not set
# CONFIG_ALEXA_WIFI_SCHEDULE_SET is not set
# CONFIG_ALEXA_WIFI_POWER_SET is not set

#
# lan
#
# CONFIG_MULTI_LAN is not set
# CONFIG_LAN_VLAN is not set
# CONFIG_LAN_PORT_VLAN is not set

#
# Lan Service
#
# WEBS_SSL_SUPPORT is not set
# CONFIG_NET_CTL_WEB_ACCESS_LAN is not set
CONFIG_MAX_LAN_PORT_NUMBER=3

#
# wan
#
CONFIG_NET_MULTI_WAN=y
# CONFIG_MULTI_DIAL is not set
CONFIG_MAX_STATIC_ROUTE_NUM=10
# CONFIG_3G is not set
# CONFIG_NET_WAN_STATIC is not set

#
# Others Dial Method
#
CONFIG_NET_WAN_PPTP=y
CONFIG_NET_WAN_L2TP=y
CONFIG_NET_DOUBLE_PPTP=y
CONFIG_NET_DOUBLE_L2TP=y
CONFIG_NET_DOUBLE_PPOE=y
# CONFIG_CHINA_NET_CLIENT is not set
CONFIG_WAN_MAX_STREAM=100

#
# DNS
#
CONFIG_ADVANCE_DDNS=y
CONFIG_ADVANCE_DYNDNS=y
# CONFIG_ADVANCE_3322 is not set
CONFIG_ADVANCE_88IP=y
CONFIG_ADVANCE_ORAY=y
# CONFIG_ADVANCE_GNWAY is not set
CONFIG_ADVANCE_NOIP=y

#
# VPN
#
CONFIG_VPN=y
CONFIG_VPN_PPTP=y
CONFIG_VPN_L2TP=y
# CONFIG_VPN_IPSEC is not set
# OPEN_SSL_SUPPORT is not set
CONFIG_VPN_CONNECT_NUMBER=15
CONFIG_VPN_USER_NUMBER=20
CONFIG_VPN_SERVER_USER_ADD_NUMBER=5
CONFIG_IPSEC_TUNNEL_NUMBER=10

#
# WAN Service
#
CONFIG_NET_CTL_WEB_ACCESS_WAN=y
# CONFIG_NET_PORT_CFG_WAN_NUMBER is not set
CONFIG_WAN_NUMBER=4
CONFIG_MAX_PHY_PORT_NUM=5

#
# TR069
#
# CONFIG_TR069_SUPPORT is not set

#
# nat
#

#
# Iptables Version
#
# CONFIG_APPS_IPTABLES_1412 is not set
# CONFIG_APPS_IPTABLES_140 is not set
# CONFIG_APPS_IPTABLES_144 is not set
CONFIG_APPS_IPTABLES=y

#
# Ebtables
#
# CONFIG_EBTABLES_TOOL is not set
CONFIG_MAX_PORT_MAP_NUM=10
CONFIG_PORT_RANGE_MAP=y

#
# Port Parameter
#
# CONFIG_NET_PORT_CFG_MIRROR is not set
CONFIG_NET_PORT_CFG_PORT_LINK_MODE=y
# CONFIG_NET_PORT_CFG_MAC_CLONE is not set

#
# Dmz
#
CONFIG_NET_DMZ=y

#
# Portal
#
# CONFIG_PORTAL_AUTH is not set
# CONFIG_WEIXIN_WIFI is not set
# CONFIG_EMAIL_CC is not set
# CONFIG_ARP_GATEWAY is not set
# CONFIG_ADD_IPGROUP_BY_HOTEL_MODE is not set
# CONFIG_ADDRESS_MASQUERADE is not set
# CONFIG_ADVANCE_P2P_NAT is not set
# CONFIG_NAT_SPEEDUP is not set
CONFIG_ADVANCE_VIRTUAL_SERVER=y
# CONFIG_ADVANCE_VIRTUAL_SERVER_TIME_OUT is not set
CONFIG_NAT_SESSION_NUMBER=8192
# CONFIG_SYSTEM_FIX_TOOL is not set
# CONFIG_POLICY_UPDATE_ONLINE is not set

#
# DHCP
#
CONFIG_NET_WAN_DHCP=y
CONFIG_LAN_DHCPC=y
CONFIG_NET_DHCP=y
CONFIG_DHCPS_LIST_MAX_NUM=20
# CONFIG_NET_DHCP_STATIC is not set
CONFIG_MAX_DHCP_CLIENT=256
CONFIG_DHCPS_STATIC_IP_NUM=32
CONFIG_BRIDGE_HANDLE_DHCP_OPTION=y

#
# PPPoE
#
CONFIG_NET_WAN_PPPOE=y
# CONFIG_PPPoE_SERVER is not set
CONFIG_AUTO_SYNCHRO=y
CONFIG_PAGE_HAVE_SERV_NAME=y

#
# led
#
CONFIG_LED_CONTROL=y
CONFIG_SCHED_LED=y
# CONFIG_USB_LED_CONTROL is not set
# CONFIG_2_4G_LED_CONTROL is not set
# CONFIG_5G_LED_CONTROL is not set
# CONFIG_INTERNET_LED is not set
CONFIG_LED_SHARE_WITH_SYS=y
# CONFIG_WIFI_LED_TENDA_KERNEL_CONTROL is not set
# CONFIG_ALEXA_LED_STATE_SET is not set
# CONFIG_ALEXA_NIGHT_MODE_SET is not set

#
# service
#
# CONFIG_CWMPD is not set
# CONFIG_DEV_COMMUNICATION is not set
# CONFIG_FASTNAT_SWITCH is not set
# CONFIG_QVLAN is not set
CONFIG_ADVANCE_UPNP=y
CONFIG_SYSTEM_SNTP=y

#
# IGMP
#
CONFIG_IGMPPROXY_SUPPORT=y
# CONFIG_IGMP_SNOOPING is not set
CONFIG_PORT_SNOOPING=y

#
# MLD
#
CONFIG_MLDPROXY_SUPPORT=y

#
# IPTV
#
CONFIG_IPTV=y
CONFIG_IPTV_STB=y

#
# cloud client
#
# CONFIG_YUN_CLIENT is not set

#
# online upgrade
#
CONFIG_UCLOUD=y
CONFIG_UCLOUD_PASSWORD=abcdef
# CONFIG_USB_SUPPORT is not set
# CONFIG_TFCARD_HOTPLUG_SUPPORT is not set
# CONFIG_URL_RCD is not set
CONFIG_MAX_CLIENT_NUM=128
# CONFIG_DLNA_SERVER is not set
CONFIG_HW_NAT=y
# CONFIG_ADVANCE_WEB_NOTIFICATION is not set
CONFIG_ROUTE_TABLE=y
# CONFIG_NET_GMAC is not set
CONFIG_MAX_SYS_LOG_NUM=250
# CONFIG_SYSTEM_UPDATE_LAYER7_PROTOCOL is not set
# CONFIG_SNMP_SERVER is not set
CONFIG_SCHED_REBOOT=y
# CONFIG_WEB_IDLE_TIME is not set
# CONFIG_DIAG_PING is not set
# CONFIG_DIAG_TRACEROUTE is not set
CONFIG_UCLOUD_FUNCTION=y
# CONFIG_SMART_POWER_MANAGEMENT is not set
# CONFIG_MASS_UPGRADE is not set
CONFIG_MIN_FREE_KBYTES=1024
# CONFIG_WLEXE is not set
# CONFIG_COMPATIBILITY is not set
# CONFIG_CROP_ENABLE is not set
# CONFIG_WEB_COMPILE_SWITCH is not set
CONFIG_CONSOLE_SWITCH=y
# CONFIG_WATCHDOG_SWITCH is not set

#
# FireWall ,QOS
#
CONFIG_KM=y

#
# FireWall
#
CONFIG_BEHAVIOR_MANAGER=y
CONFIG_GROUP_IP_NUMBER=30
CONFIG_GROUP_TIMER_NUMBER=30
CONFIG_DEFAULT_IP_GROUP_NUMBER=1
CONFIG_DEFAULT_TIME_GROUP_NUMBER=1

#
# FILTER  Advanced Configurations
#
CONFIG_FILTER_MAC=y
CONFIG_FILTER_MAC_NUMBER=100
# CONFIG_FILTER_IPMAC is not set
CONFIG_BIND_IPMAC_NUMBER=100
# CONFIG_CONNECT_LIMIT is not set
# CONFIG_IP_FILTER is not set
CONFIG_FILTER_IP_NUMBER=20
CONFIG_PRIVILEGE_IP=y
# CONFIG_FILTER_IPPORT is not set
CONFIG_FILTER_IPPORT_NUMBER=20
CONFIG_FILTER_URL=y
CONFIG_FILTER_URL_NUMBER=20
CONFIG_URL_GROUP_NUMBER=10
CONFIG_GROUP_URL_NUMBER=20
CONFIG_URL_FILTER_SYSTEM_CLASSES_SUPPORT=y
CONFIG_ONLINE_IP=y
CONFIG_ONLINE_IP_NUMBER=384
# CONFIG_APP_IDENTIFY is not set
# CONFIG_FILTER_APP is not set
# CONFIG_ACCOUNT_MANAGE is not set
CONFIG_WAN_POLICY_NUMBER=20

#
# QOS
#
CONFIG_QOS=y
CONFIG_QOS_RULE_NUMBER=20
# CONFIG_PORTAL_QOS is not set

#
# NOS Control
#
# CONFIG_NOS_CONTROL is not set

#
# Safe
#
CONFIG_SAFE_ATTACK=y
CONFIG_SAFE_ARP=y
# CONFIG_WAN_ICMP_DROP is not set
# CONFIG_DNS_REDIRECT is not set

#
# ac_management
#
# CONFIG_AP_MANAGE is not set

#
# ate
#
CONFIG_ATE_AES_CBC_ENCRYPT=y

#
# mac vendor
#
CONFIG_SCHED_MAC_VENDOR=y

#
# offline log
#
# CONFIG_SCHED_OFFLINE_LOG is not set

#
# select ISP
#
CONFIG_SELECT_ISP=y

#
# force upgrade
#
CONFIG_SCHED_FORCE_UPGRADE=y

#
# daylight saving time
#
CONFIG_DAYLIGHTSAVINGTIME=y
CONFIG_AP_MODE=y

#
# Tenda Easymesh
#
CONFIG_TENDA_EASYMESH=y

#
# Tenda Easymesh
#
CONFIG_TENDA_XMESH=y
CONFIG_PLATFORM_MSG=y
# CONFIG_CBRR is not set

#
# Syschk
#
CONFIG_TENDA_SYSCHK=y
CONFIG_WIFI_SUPPORT_APCLIENT=y
CONFIG_WIFI_SUPPORT_WISP=y
