#ifndef __AUTOCONF_UFILTER_H__
#define __AUTOCONF_UFILTER_H__

//#define NETLINK_BEHAVE_MANGLE 20
#define BM_RULE_REFRESH_INTERVAL 30
#define MAX_IP_GROUP_COUNT 30
#define DEFAULT_GLOBAL_IP_GROUP_INDEX 22
#define MAX_IP_SEGMENT 10
#define MAX_MAC_MEMBER 32
#define MAX_MAC_GROUP_COUNT 32
#define MAX_MAC_FILTER_NUM          10
#define MAX_IP_MAC_PAIR_NUM         10
#define TIME_GROUP_NUM 30
#define TIME_RANGE_COUNT_MAX 10
#define MAX_FILTER_PROTO_RULE_NUMBER 30
#define URL_FILTER_COUNT_MAX 30
#define MAX_PRIVILEGE_IP_RULE_NUMBER 30
#define MAC_FILTER_COUNT_MAX 199
#define IPMACBIND_FILTER_SIZE 199
#define APP_FILTER_COUNT_MAX 30
#define IPPORT_FILTER_COUNT_MAX 30
#define MAX_PORT_FILTER_SIZE 10
#define ACCOUNT_INFO_STR_LEN 64
#define MAX_ACCOUNT_RULE_NUMBER 50
#define MAX_OBJ_NAME 32
#define MAX_OBJ_DESC 32
#define MAX_DEFINE_URL_SIZE 32
#define MAX_DEFINE_URL_COUNT 32
#define MAX_GLOBAL_URL_GROUP 70
#define MAX_URL_LEN 64
#define MAX_APP_COUNT 256
#define DHCP_RESERVE_IP_COUNT 100
#define WAN_POLICY_COUNT 30

#endif

